config/routes.rb
Shop::Application.routes.draw do

  get "payments/cancel"
  get "payments/success"
  get "payments/notify"
  resources :item_users, only: [:index, :create, :destroy, :update]
  resources :orders, only: [:index, :create, :show]
  get 'payments/cancel'
  match 'payments/success', via: [:get, :post]
  match 'payments/notify', via: [:get, :post, :put]

  devise_for :users

	root 'about#description'

	resources	:categories

	resources	:contacts

	resources	:posts

	resources	:members

  resources :comments, only: [:new, :create]

  resources :items

end

app/models/category.rb
class Category < ActiveRecord::Base

# Associations
  has_many :items, dependent: :nullify

  validates :name, presence: true, format:  {
    with: /\A[a-zA-Z]+\z/,
    message: "Only letters allowed!"
  }, length: {
    minimum: 3
  }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :item
  validates :message, :name, presence: true
  validates :message, uniqueness: true
  validates :rating, numericality: { greater_than: 0, less_than_or_equal_to: 5, only_integer: true }
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name,  :phone, :email, presence: true
  validates :name,  :address, format: {
    with: /[0-9а-яА-Яa-zA-Z.,]{3,}\z/,
    message: "Wrong..."
  }
  validates :phone, format: {
    with: /\+\d{10,}\b/,
    message: "Doesn't match the format! (+7123456789)"
  }
  validates :website, format: {
    with: /\w{2,}\.\w{2,}\.\w{2,5}\b/,
    message: "Doesn't match the format! (www.example.com)"
  }
end

app/models/item.rb
class Item < ActiveRecord::Base
# Associations
  belongs_to  :category
  has_many    :comments, dependent: :destroy
  has_many    :item_users, dependent: :destroy
  has_many    :item_orders, dependent: :destroy

# Validations
  validates :name, :price, presence: true
  validates :name, uniqueness: true
  validates :price, numericality: {
    greater_than_or_equal_to: 0.01
  }
  validates :name, length: {
    minimum:  2
  }

#
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100#" }, default_url: "/system/items/photos/:style/missing.png"

  def ratingBadge
    if rating
      if rating >= 4
        'success'
      elsif rating > 2
        'warning'
      else
        'important'
      end
    end
  end
end

app/models/item_order.rb
class ItemOrder < ActiveRecord::Base
  # Associations
  belongs_to :order
  belongs_to :item

  # Validations
  validates :order_id, :quantity, :item_id, :price, presence: true
  validates :order_id, :item_id, :quantity, numericality: { only_integer: true, greater_than: 0 }
  validates :price, numericality: { greater_than: 0 }
end

app/models/item_user.rb
class ItemUser < ActiveRecord::Base

  # Associations
  belongs_to :item
  belongs_to :user

  # Validations
  validates :item_id, :user_id, :quantity, presence: true, numericality: {
    only_integer: true,
    greater_than: 0
  }

  # Custom methods
  def self.total_price(user)
  	total = 0.0
  	user.item_users.each do |i|
  		total += i.full_price
  	end
  	total
  end

  def full_price
    quantity * item.price
  end

end

app/models/member.rb
class Member < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base

  # Associations
  belongs_to :user
  has_many :item_orders, dependent: :destroy

  # Validations
  validates :user_id, :price, presence: true
  validates :user_id, numericality: { only_integer: true, greater_than: 0 }
  validates :price, numericality: { greater_than: 0 }

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Associations
  has_many    :item_users, dependent: :destroy
  has_many    :orders, dependent: :destroy

  # Validations
  # validates

  # Custom methods
  def full_price
    self.item_users.quantity * self.item_users.item.price
  end
  def totalCartPrice
    total = 0
    self.item_users.each do |i|
      total += i.item.price * i.quantity
    end
    total
  end

  def cartQ
    total = 0
    self.item_users.each do |i|
      total += i.quantity
    end
    total
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  # Before listed action use method for them
  before_filter :authenticate_user!, except: [:index, :show]

  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.order(name: :asc)
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @comment = Comment.new
    @comment.item_id = @item.id

    @item_user = ItemUser.new
    @item_user.item_id = @item.id
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to items_path, notice: 'Item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to items_path, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:price, :name, :description, :special, :category_id, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/item_users_helper.rb
module ItemUsersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sitemap_helper.rb
module SitemapHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= simple_form_for(@item) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :price %>
    <%= f.input :description %>
    <%= f.input :special %>
    <%= f.input :photo %>

    <%= f.input :category_id, collection: Category.order(name: :asc) %>
  </div>

  <%= f.button :submit, class: 'btn btn-primary' %>
  <%= link_to 'Back', items_path, class: 'btn btn-inverse pull-right' %>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

app/views/items/index.html.erb
<h1>Items</h1>

<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Rating</th>
      <th>Price</th>
      <%  if signed_in?  %>
        <th></th>
        <th></th>
      <%  end  %>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= link_to item.name, item %></td>
        <td><%= item.rating %></td>
        <td><%= item.price %></td>
        <%  if signed_in?  %>
          <td><%= link_to 'Edit', edit_item_path(item) %></td>
          <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%  end  %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%  if signed_in?  %>
  <%= link_to 'Add Item', new_item_path, class: 'btn btn-primary' %>
<%  end  %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

app/views/items/show.html.erb
<%  if signed_in?  %>

  <%=  simple_form_for @item_user do |f|  %>
    <%=  f.input :item_id, as: :hidden %>
    <%=  f.submit 'Add to cart', class: 'btn btn-primary pull-right' %>
  <%  end  %>

  <%= link_to 'Edit', edit_item_path(@item), class: 'btn btn-primary' %>

<%  end  %>


<%  if @item.category.present?  %>
  <%= link_to "Back", @item.category, class: 'btn pull-right btn-inverse' %>
<%  else  %>
  <%= link_to "Back", categories_path, class: 'btn pull-right btn-inverse'  %>
<%  end %>
<h1><%= @item.name  %></h1>

<%= image_tag @item.photo(:thumb) %>

<%  if @item.category.present?    %>
  <p>Category: <%=  @item.category.name %></p>
<%  end %>

<p>
  <strong>Rating:</strong>
  <%  if @item.rating %>
    <%= "%.2f" % @item.rating %>
  <%  else  %>
    No rating for now!
  <%  end %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %> $
</p>

<p>
  <strong>Name:</strong>
  <%= @item.name  %>
</p>

<p><%=  @item.description %></p>

<%  if @item.special.present? %>
  <p class="alert alert-success"><%=  @item.special %></p>
<%  end %>


<h3>Add a comment</h3>

<%= render 'comments/form' %>

<h3>All comments</h3>

<% @item.comments.each do |comment| %>
  <div class="row well">
    <div class="span2"><b><%= comment.name  %></b></div>
    <div class="span4"><em><%=  comment.message %></em></div>
    <div class="span1">
      <%  if comment.rating >= 4
        badge = 'success'
      elsif comment.rating > 2
        badge = 'warning'
      else
        badge = 'important'
      end %>
        <span class="badge badge-<%= badge %>"><%= comment.rating  %></span>
    </div>
  </div>
<% end %>