config/routes.rb
Shop::Application.routes.draw do

  get "payments/cancel"
  get "payments/success"
  get "payments/notify"
  resources :item_users, only: [:index, :create, :destroy, :update]
  resources :orders, only: [:index, :create, :show]
  get 'payments/cancel'
  match 'payments/success', via: [:get, :post]
  match 'payments/notify', via: [:get, :post, :put]

  devise_for :users

	root 'about#description'

	resources	:categories

	resources	:contacts

	resources	:posts

	resources	:members

  resources :comments, only: [:new, :create]

  resources :items

end

app/models/category.rb
class Category < ActiveRecord::Base

# Associations
  has_many :items, dependent: :nullify

  validates :name, presence: true, format:  {
    with: /\A[a-zA-Z]+\z/,
    message: "Only letters allowed!"
  }, length: {
    minimum: 3
  }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :item
  validates :message, :name, presence: true
  validates :message, uniqueness: true
  validates :rating, numericality: { greater_than: 0, less_than_or_equal_to: 5, only_integer: true }
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name,  :phone, :email, presence: true
  validates :name,  :address, format: {
    with: /[0-9а-яА-Яa-zA-Z.,]{3,}\z/,
    message: "Wrong..."
  }
  validates :phone, format: {
    with: /\+\d{10,}\b/,
    message: "Doesn't match the format! (+7123456789)"
  }
  validates :website, format: {
    with: /\w{2,}\.\w{2,}\.\w{2,5}\b/,
    message: "Doesn't match the format! (www.example.com)"
  }
end

app/models/item.rb
class Item < ActiveRecord::Base
# Associations
  belongs_to  :category
  has_many    :comments, dependent: :destroy
  has_many    :item_users, dependent: :destroy
  has_many    :item_orders, dependent: :destroy

# Validations
  validates :name, :price, presence: true
  validates :name, uniqueness: true
  validates :price, numericality: {
    greater_than_or_equal_to: 0.01
  }
  validates :name, length: {
    minimum:  2
  }

#
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100#" }, default_url: "/system/items/photos/:style/missing.png"

  def ratingBadge
    if rating
      if rating >= 4
        'success'
      elsif rating > 2
        'warning'
      else
        'important'
      end
    end
  end
end

app/models/item_order.rb
class ItemOrder < ActiveRecord::Base
  # Associations
  belongs_to :order
  belongs_to :item

  # Validations
  validates :order_id, :quantity, :item_id, :price, presence: true
  validates :order_id, :item_id, :quantity, numericality: { only_integer: true, greater_than: 0 }
  validates :price, numericality: { greater_than: 0 }
end

app/models/item_user.rb
class ItemUser < ActiveRecord::Base

  # Associations
  belongs_to :item
  belongs_to :user

  # Validations
  validates :item_id, :user_id, :quantity, presence: true, numericality: {
    only_integer: true,
    greater_than: 0
  }

  # Custom methods
  def self.total_price(user)
  	total = 0.0
  	user.item_users.each do |i|
  		total += i.full_price
  	end
  	total
  end

  def full_price
    quantity * item.price
  end

end

app/models/member.rb
class Member < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base

  # Associations
  belongs_to :user
  has_many :item_orders, dependent: :destroy

  # Validations
  validates :user_id, :price, presence: true
  validates :user_id, numericality: { only_integer: true, greater_than: 0 }
  validates :price, numericality: { greater_than: 0 }

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Associations
  has_many    :item_users, dependent: :destroy
  has_many    :orders, dependent: :destroy

  # Validations
  # validates

  # Custom methods
  def full_price
    self.item_users.quantity * self.item_users.item.price
  end
  def totalCartPrice
    total = 0
    self.item_users.each do |i|
      total += i.item.price * i.quantity
    end
    total
  end

  def cartQ
    total = 0
    self.item_users.each do |i|
      total += i.quantity
    end
    total
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_filter :authenticate_user!, except: [:index, :show]

  layout  'application'

  def index
    @categories = Category.order(name: :asc)
  end

  def new
    @category = Category.new  # @ means that this variable is seen inside the VIEW file
    b = 1           # this variable's scope is this DEF only
  end

  def create
    @category = Category.new(params[:category].permit(:name)) # params is all data from user; params[:{modelName}] filters them by model; permit gives permission to record data for named fields
    if  @category.save
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
    # Find a category by id
    # params is an object that is got from web
    @category = Category.find(params[:id])
  end

  def update
    # Find a record
    @category = Category.find(params[:id])

    # Update props
    if @category.update_attributes params[:category].permit(:name)
      # Goto catlist
      redirect_to categories_path
    else
      render 'edit'
    end
  end

  def destroy
    # Find a record
    @category = Category.find(params[:id])
    # Destroy record
    @category.destroy
    # Goto catlist
    redirect_to categories_path
  end

  def show
    @cat  = Category.find(params[:id])
    @all  = Category.order(name: :asc)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/item_users_helper.rb
module ItemUsersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sitemap_helper.rb
module SitemapHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for @category do |f|  %>
  <%= f.input :name %>
  <%= f.button :submit, class: 'btn btn-primary'  %>
  <%= link_to 'Back', categories_path, class: 'btn pull-right btn-inverse'  %>
<%  end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%=	render 'form'	%>

app/views/categories/index.html.erb
<h1>Categories</h1>

<table class="table-striped table-hover table">
  <!-- <caption>Goods</caption> -->
  <%  @categories.each do |cat| %>
    <%  if cat.items.any? %>
      <tr>
        <td><b><%=  link_to cat.name, category_path(id: cat.id) %></b></td>
        <%  if signed_in?  %>
          <td><%= link_to 'Edit category', edit_category_path(id: cat.id) %></td>
          <td><%= link_to 'Delete', cat, method: :delete, confirm: 'Sure?'  %></td>
        <%  end  %>
      </tr>
    <%  end %>
  <%  end %>
</table>

<%  if signed_in?  %>
  <%= link_to 'Add one', new_category_path, class: 'btn btn-primary'  %>
<%  end  %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%=	render 'form'	%>

app/views/categories/show.html.slim
h1 = @cat.name

- @cat.items.each do |item|
  .item-card
    .name
      = link_to item.name, item
      - if item.rating
        div class="pull-right badge badge-#{item.ratingBadge}"
          = "%.2f" % item.rating

    .price = item.price
    .photo = link_to image_tag(item.photo(:thumb)), item

.footer
  = link_to 'Add Item', new_item_path, class: 'btn btn-primary pull-left'
  = link_to 'Back', categories_path, class: 'btn pull-right btn-inverse'

app/views/categories/sssshow.html.erb
<h1><%= @cat.name %></h1>

<%  @cat.items.each do |item| %>
  <%  if item.rating && item.rating >= 4
    badge = 'success'
  elsif item.rating && item.rating > 2
    badge = 'warning'
  else
    badge = 'important'
  end %>
  <div class="item-card">
    <div class="name"><%= link_to item.name, item %>
      <%  if item.rating  %>
        <div class="pull-right badge badge-<%= badge %>"><%=  "%.2f" % item.rating %></div>
      <%  end  %>
    </div>
    <div class="price"><%=  item.price  %> $</div>
    <div class="photo"><%=  link_to (image_tag item.photo(:thumb)), item  %></div>
  </div>
<%  end %>

<div class="footer">
  <%= link_to 'Add Item', new_item_path, class: 'btn btn-primary pull-left' %>
  <%= link_to 'Back', categories_path, class: 'btn pull-right btn-inverse'  %>
</div>