config/routes.rb
Shop::Application.routes.draw do

  get "payments/cancel"
  get "payments/success"
  get "payments/notify"
  resources :item_users, only: [:index, :create, :destroy, :update]
  resources :orders, only: [:index, :create, :show]
  get 'payments/cancel'
  match 'payments/success', via: [:get, :post]
  match 'payments/notify', via: [:get, :post, :put]

  devise_for :users

	root 'about#description'

	resources	:categories

	resources	:contacts

	resources	:posts

	resources	:members

  resources :comments, only: [:new, :create]

  resources :items

end

app/models/category.rb
class Category < ActiveRecord::Base

# Associations
  has_many :items, dependent: :nullify

  validates :name, presence: true, format:  {
    with: /\A[a-zA-Z]+\z/,
    message: "Only letters allowed!"
  }, length: {
    minimum: 3
  }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :item
  validates :message, :name, presence: true
  validates :message, uniqueness: true
  validates :rating, numericality: { greater_than: 0, less_than_or_equal_to: 5, only_integer: true }
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name,  :phone, :email, presence: true
  validates :name,  :address, format: {
    with: /[0-9а-яА-Яa-zA-Z.,]{3,}\z/,
    message: "Wrong..."
  }
  validates :phone, format: {
    with: /\+\d{10,}\b/,
    message: "Doesn't match the format! (+7123456789)"
  }
  validates :website, format: {
    with: /\w{2,}\.\w{2,}\.\w{2,5}\b/,
    message: "Doesn't match the format! (www.example.com)"
  }
end

app/models/item.rb
class Item < ActiveRecord::Base
# Associations
  belongs_to  :category
  has_many    :comments, dependent: :destroy
  has_many    :item_users, dependent: :destroy
  has_many    :item_orders, dependent: :destroy

# Validations
  validates :name, :price, presence: true
  validates :name, uniqueness: true
  validates :price, numericality: {
    greater_than_or_equal_to: 0.01
  }
  validates :name, length: {
    minimum:  2
  }

#
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100#" }, default_url: "/system/items/photos/:style/missing.png"

  def ratingBadge
    if rating
      if rating >= 4
        'success'
      elsif rating > 2
        'warning'
      else
        'important'
      end
    end
  end
end

app/models/item_order.rb
class ItemOrder < ActiveRecord::Base
  # Associations
  belongs_to :order
  belongs_to :item

  # Validations
  validates :order_id, :quantity, :item_id, :price, presence: true
  validates :order_id, :item_id, :quantity, numericality: { only_integer: true, greater_than: 0 }
  validates :price, numericality: { greater_than: 0 }
end

app/models/item_user.rb
class ItemUser < ActiveRecord::Base

  # Associations
  belongs_to :item
  belongs_to :user

  # Validations
  validates :item_id, :user_id, :quantity, presence: true, numericality: {
    only_integer: true,
    greater_than: 0
  }

  # Custom methods
  def self.total_price(user)
  	total = 0.0
  	user.item_users.each do |i|
  		total += i.full_price
  	end
  	total
  end

  def full_price
    quantity * item.price
  end

end

app/models/member.rb
class Member < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base

  # Associations
  belongs_to :user
  has_many :item_orders, dependent: :destroy

  # Validations
  validates :user_id, :price, presence: true
  validates :user_id, numericality: { only_integer: true, greater_than: 0 }
  validates :price, numericality: { greater_than: 0 }

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Associations
  has_many    :item_users, dependent: :destroy
  has_many    :orders, dependent: :destroy

  # Validations
  # validates

  # Custom methods
  def full_price
    self.item_users.quantity * self.item_users.item.price
  end
  def totalCartPrice
    total = 0
    self.item_users.each do |i|
      total += i.item.price * i.quantity
    end
    total
  end

  def cartQ
    total = 0
    self.item_users.each do |i|
      total += i.quantity
    end
    total
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sitemap_helper.rb
module SitemapHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.slim
html
  head
    title Ruby-on-Rails Shop
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .container
      .navbar
        .navbar-inner
          ul.nav
            li= link_to 'Main', root_path
            li.divider-vertical
            li= link_to t('navbar.goods'),categories_path
            li.divider-vertical
            li= link_to t('navbar.team'), members_path
            li.divider-vertical
            li= link_to t('navbar.contacts'), contacts_path
            li.divider-vertical
            li= link_to t('navbar.blog'), posts_path
          - if signed_in?
            = link_to t('navbar.logout'), destroy_user_session_path, method: :delete, class: 'btn btn-inverse pull-right unclear'
            = link_to t('cart'), item_users_path, class: 'btn btn-info clearfix pull-right unclear'
            = link_to t('navbar.orders'), orders_path, class: 'btn btn-success clearfix pull-right unclear' if current_user.orders.any?

      .row
        .span7
          - if notice
            p.notice = notice
          - if alert
            p.alert = alert
          = yield

        .span5
          .hero-unit style='height: 500px'
            - if signed_in?
              p= t('hello')
              p
                = t('sidebar.greetings') + ', '
                = current_user.email
              div
                = link_to t('cart'), item_users_path, class: ''
                = " - #{ current_user.cartQ } "
                = "#{ t('items') } - "
                =  "$ #{ current_user.totalCartPrice }"

            - else
              p
                = t('sidebar.unknown')
                = link_to 'Sign up', new_user_registration_path, class: 'btn btn-primary'
                = t('sidebar.met?')
                = link_to "Sign in", new_user_session_path, class: 'btn btn-primary'

      .footer